### ISSUE TITLE
Possible to add "expire" and "retry" as inputform?

### ISSUE THREAD

**Issue by Aals0n** [damoclark/node-red-node-pushover#1]
Hello everyone,

first of all - I really like the implementation of the pushover API for Node Red! I have a question about a missing input variable for my usecase:

Is it possible to add the following `retry` and `expire` from the [Pushover API](https://pushover.net/api#priority)?
I'd like to help, but i'm not really shure how to implement that. Maybe someone else could help?

Thanks for sharing your work!

**Comment by damoclark** [comment]
Hi @trise-ne 

This experimental node was merged into the standard Node Red distribution.  You could submit your request via the Node Red forums to see if the team is able to implement the features.

Cheers,
Damien,
